### ISSUE TITLE
Link migration to git tag or commit

### ISSUE THREAD

**Issue by ghost** [camptocamp/marabunta#28]
If we check out latest commit and play all migrations it seems like it not chronologically correct migrations because in different time code-slice looks differently.

Example:
```
     v1     v2     v3
-----*------*------*-----> 
     t1     t2     t3    time
```
In `t1` we create migration `v1` and code contain lines
```
...
name = field.Char()
...
```
To the moment `t2` we add more code and create migration `v2`
```
...
name = field.Char()
age = field.Integer()
...
```
To the moment `t3` we introduce new changes and create migration `v3`
```
...
person_id = field.Many2one(...)
...
```
If we need to run all migration on the new server we check out `v3` code and on `v1`  we already install code that should be migrated late. and in the moment of `v2` migration, we receiving an error because the code hasn't appropriate fields.

**Comment by guewen** [comment]
@oleksandrpaziuk absolutely, this is why by default you cannot run more than one version at a time. You are supposed to load the container of version t1, run the migration, load the container of version t2, run the migration and so on. For dev, we authorize to run migrations sequentially for our comfort, hoping we don't hit this issue.

IMO we can't do anything, the culprit is odoo which ties the migration to the code. In systems such as sqlalchemy with alembic, they are not coupled so you can run all the steps in the migration even if your code is the most recent one.

**Comment by oleksandrpaziuk** [comment]
I think we can add `tag` and `commit` options to `migration.yml`. They should be optional. And execute `git checkout ...` for repo.

Example:
`tag` variant
```
...
    - version: 10.1
      tag: v10.1
      addons:
        upgrade:
...
```

`commit` variant
```
...
    - version: 10.2
      commit: 7a26082d417cd5f1396653e3b93b6c45178477a2
      addons:
        upgrade:
...
```
In this case we at least will provide the integrity of what is happening.

Or it totally wrong idea?

**Comment by guewen** [comment]
We work with docker images and inside the docker images we don't keep the `.git` history.
I think what you should do if such case happen is to adapt the migration code of `t1` and `t2` in the last version `t3` to handle this case.
